[package]
name = "sscanf_macro"
version = "0.4.0"
authors = ["mich101mich <mich101mich@gmail.com>"]
edition = "2018"
description = "Proc-Macros for the sscanf Crate. Not meant to be used as a standalone Crate"
repository = "https://github.com/mich101mich/sscanf"
readme = "Readme.md"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.50", features = ["parsing", "derive", "full"] }
quote = "1.0.0"
proc-macro2 = "1.0.0"
regex-syntax = "0.6.0"
unicode-width = "0.1.5"
