[package]
name = "sscanf_macro"
version = "0.4.1"
authors = ["mich101mich <mich101mich@gmail.com>"]
edition = "2018"
rust-version = "1.56.0"
description = "Proc-Macros for the sscanf Crate. Not meant to be used as a standalone Crate"
repository = "https://github.com/mich101mich/sscanf"
readme = "Readme.md"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.1", features = ["parsing", "derive", "full"] }
quote = "1.0.0"
proc-macro2 = "1.0.0"
regex-syntax = "0.6.0"
unicode-width = "0.1.5"
strsim = "0.10.0"
convert_case = "0.6.0"
