name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.2.0
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
    - name: Run tests
      run: cargo test
    - name: Run feature tests
      run: cargo test --all-features
    - name: Run nightly tests
      run: cargo +nightly test
    - name: Run nightly feature tests
      run: cargo +nightly test --all-features
    - name: Run docs
      run: export RUSTDOCFLAGS="--cfg doc_cfg" && cargo +nightly doc --all-features
