name: Tests

on:
  push: { branches: [ master ] }
  pull_request: { branches: [ master ] }

env:
  CARGO_TERM_COLOR: always

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/toolchain@v1.0.6
      with: { toolchain: stable }
    - name: Run tests
      run: cargo +stable test

  nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/toolchain@v1.0.6
      with: { toolchain: nightly }
    - name: Run tests
      run: cargo +nightly test
    - name: Run docs
      run: cargo +nightly doc --no-deps

  minimal-versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/toolchain@v1.0.6
      with: { toolchain: stable }
    - uses: actions-rs/toolchain@v1.0.6
      with: { toolchain: nightly }
    - name: Update to minimal versions
      run: cargo +nightly update -Z minimal-versions
    - name: Run minimal version tests
      run: cargo +stable test -- --skip failing_tests
    - name: Run minimal version nightly tests
      run: cargo +nightly test -- --skip failing_tests

  minimum-rust-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/toolchain@v1.0.6
      with: { toolchain: 1.56.0 }
    - name: Run tests
      run: cargo +1.56.0 test -- --skip failing_tests
